### ISSUE TITLE
Need to generate IPLD codec type for logs

### ISSUE THREAD

**Issue by stellarmagnet** [vulcanize/go-codec-dageth#25]

**Comment by i-norden** [comment]
In Ethereum logs are not content-hash referenced, they are just stored in an array in their parent receipt. We would like to expand them into their own merkle dag in IPLD, so that we can do compact inclusion proofs for individual logs.

We will construct a merkle tree out of the logs, with each log in the array being stored in a leaf, and in the IPLD representation of the receipt we will reference the root of this tree rather than including an array of logs

**Comment by i-norden** [comment]
I think we should go ahead and use a MMPT in the same manner as the ones used for txs and receipts, so that we can also do exclusion proofs and stay consistent with the other tries in Ethereum.

**Comment by i-norden** [comment]
Closed in #27
